name: Test React App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - name: Install Dependencies
      run: yarn install --cwd ClientApp
    - name: Run Tests
      run: yarn test --cwd ClientApp
